source 'https://rubygems.org'

ruby '2.6.3'

gem 'sinatra', '3.0.4'
gem 'sinatra-contrib', '3.0.4'

gem 'sinatra-activerecord', '~> 2.0'
gem 'rake'
gem 'nokogiri'
gem 'sqlite3'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
